### ISSUE TITLE
Microsoft azure

### ISSUE THREAD

**Issue by smartkidag** [asapach/peerflix-server#101]
While deploying with docker on azure, it's not working. when I finish the code, it just gives me a value like 
ff4b5f3d826ad00a268a8ff789be5b2390a7f0e1d110a711cbf9629a803bb759 and that's it. It doesnt open. What does this mean?

**Comment by asapach** [comment]
I haven't used it in a while, but I think it's the container name when you run it [detached mode](https://docs.docker.com/engine/reference/run/#/detached--d).
You can also try running it foreground mode using the second line here: https://github.com/asapach/peerflix-server/blob/master/Docker.md
