### ISSUE TITLE
Using azure with peerflix

### ISSUE THREAD

**Issue by smartkidag** [asapach/peerflix-server#102]
Using VM on azure to setup peerflix and then tunnel to the internet. I tried and it works fine.

**Comment by asapach** [comment]
Yeah, but I got a DMCA takedown notice on Azure once, so be aware.

**Comment by smartkidag** [comment]
But how am i supposed to use the server after closing the terminal I used nohup but it doesnt work. 
I used it like this:
nohup peerflix-server &
This is the only thing I'm stuck at right now.

**Comment by smartkidag** [comment]
Found the solution. I used Screen command. It's working fine now. :)
