### ISSUE TITLE
An easier way to add password protection

### ISSUE THREAD

**Issue by n00b12345** [asapach/peerflix-server#104]
At present, the process is a little convoluted. A simpler method of enabling password protection would really be helpful.

Please consider.

**Comment by DarkVenusNet** [comment]
If you're still interested [try this](https://github.com/asapach/peerflix-server/wiki/How-to-put-a-password-on-peerflix-server-using-basic-auth)

**Comment by n00b12345** [comment]
@DarkVenusNet Thank you so much for the help :)

**Comment by asapach** [comment]
@DarkVenusNet, maybe you could create a fork to make the customization easier?
