### ISSUE TITLE
Add a link "download zip" when all files are downloaded

### ISSUE THREAD

**Issue by PLhery** [asapach/peerflix-server#105]
Some torrents contain a lot of files and it would be great it we could download them all in a single zip. For the moment I use cakebox (with peerflix folder) which has this feature, but it's the only reason I use cakebox.

**Comment by asapach** [comment]
related to #40

**Comment by dachinat** [comment]
Perhaps a 'live' version of zip is possible, to download zip when files are still in progress.

**Comment by asapach** [comment]
As a workaround: all the files in a torrent are downloaded locally in temp folder anyway:
* On Linux/MacOS: `/tmp/torrent-stream`
* On Windows: `%TEMP%\torrent-stream`

**Comment by leonrocha** [comment]
No one had a solution? zip download all files.

**Comment by dachinat** [comment]
Would be great if this gets implemented...

**Comment by asapach** [comment]
OK, I've had some free time to work on this. The torrent title in the header is now a link to the zip archive.

![image](https://user-images.githubusercontent.com/1755336/43681289-e9523bea-9857-11e8-80a8-fa1954aa5f90.png)

Please install the latest version and see if it works for you.

**Comment by dachinat** [comment]
Wow, I was working on this at the moment. Very happy! 
<img width="514" alt="screen shot 2018-08-05 at 3 37 55 am" src="https://user-images.githubusercontent.com/22872749/43681327-06205d02-9861-11e8-9e32-db347a052f07.png">

**Comment by dachinat** [comment]
@asapach So far it works great. Thanks a lot! Owe you for this!
I was trying to use `node-archiver` too, but I had some problems with streams and was struggling with `tailing-stream`, you did a great job!

**Comment by asapach** [comment]
Thanks, @dachinat

**Comment by dachinat** [comment]
@asapach Do you have an address that you can share? I can send you some of our national food. It's kind of sweet, made from thickened grape-juice ([see pictures](https://www.google.com/search?biw=1323&bih=748&tbm=isch&sa=1&ei=LUBmW9WJE4n9kwXv2ZigBA&q=%E1%83%A9%E1%83%A3%E1%83%A0%E1%83%A9%E1%83%AE%E1%83%94%E1%83%9A%E1%83%90&oq=%E1%83%A9%E1%83%A3%E1%83%A0%E1%83%A9%E1%83%AE%E1%83%94%E1%83%9A%E1%83%90&gs_l=img.3..0l4j0i30k1j0i5i30k1.1530.2659.0.2729.8.7.0.0.0.0.140.519.0j4.4.0....0...1c.1.64.img..4.4.518....0.-bo0yqcoP_E)) I think you're going to like.
