### ISSUE TITLE
how to deploy this respository to heroku???

### ISSUE THREAD

**Issue by jiorohan1** [asapach/peerflix-server#109]

**Comment by asapach** [comment]
As explained in #98 I think it's no longer possible.

You can try an older version: https://github.com/asapach/peerflix-server/tree/v0.1.2

**Comment by jiorohan1** [comment]
app is creating but after sometime it disappers. And comes NO SUCH APP.

**Comment by GautierT** [comment]
I guess Heroku don't want people to download illegal file with their servers...

**Comment by nk932715** [comment]
any other free alternative ?
