### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by next2non** [asapach/peerflix-server#112]
Hi 

I have just couple of questions:

1. When I click at the cross (x) after the file finishes downloading, does it delete the file as well from my device? Currently running it on Synology

2. If the clicking on the cross (x) doesn't delete the file, how do I delete it? Where is it located? 

Regards,
Tariq

**Comment by asapach** [comment]
1. Yes, the files should be deleted unless they are locked (this is usually only a problem on windows).
2. By default the files are stored in `/tmp/torrent-stream`. If `/tmp` doesn't exist it will try to find another temp folder. BTW, you can set your own folder: https://github.com/asapach/peerflix-server#configuration

**Comment by next2non** [comment]
Hi

Thanks for the reply. 

I created a /tmp folder in synology and "torrent-stream" folder appears in it, but when the torrent download is completes the folder is empty. Any reasons you could think of? By the way I'm running the package from docker m.

**Comment by asapach** [comment]
I haven't used docker in a while, but as far as I remember, you need to map the `/tmp/torrent-stream` volume to your local folder, otherwise it will only be stored inside your container: https://github.com/asapach/peerflix-server/blob/master/Docker.md

**Comment by next2non** [comment]
Now it's working, I was mapping "/tmp" to my local drive whereas I need to map "/tmp/torrent-stream". Thanks for the help and you time

**Comment by asapach** [comment]
Thanks. I've added more explicit instructions in https://github.com/asapach/peerflix-server/commit/88047aa70518ff197646f10c95d6f653a902f066
