### ISSUE TITLE
Update torrent-stream dependency

### ISSUE THREAD

**Issue by hex2a** [asapach/peerflix-server#114]
when installing using npm, this warning appears:
`npm WARN deprecated bittorrent-dht@3.2.6: Critical security issue fixed in 5.1.3. All users should upgrade. (More info: https://github.com/feross/bittorrent-dht/issues/87)`

this seems to be due to an outdated torrent-stream version
 └─┬ torrent-stream@0.18.1
    ├── bitfield@0.1.0
    ├─┬ bittorrent-dht@3.2.6

**Comment by asapach** [comment]
Yeah, we're so far behind that there are probably some breaking changes. But I'll see if this can be done.

**Comment by asapach** [comment]
Released as v0.2.0. No breaking changes that I can see.
