### ISSUE TITLE
downloading does't start, Please look at screenshot

### ISSUE THREAD

**Issue by nk932714** [asapach/peerflix-server#119]
![image](https://user-images.githubusercontent.com/29853208/29494104-c8789aae-85c0-11e7-8248-a8de457a6289.png)

Any solution for this why downloading is not starting.

**Comment by asapach** [comment]
It looks like there aren't any peers. This happens with unpopular torrents or private trackers. Try another torrent client and see if it works better.

**Comment by nk932714** [comment]
![image](https://user-images.githubusercontent.com/29853208/29494597-4c5938ce-85cb-11e7-8174-45fd9193de6b.png)

please check this screenshot i think this torrent has enough seeds and leechs

**Comment by asapach** [comment]
Sorry, I'm not going to troubleshoot your issues based on screenshots.

**Comment by nk932714** [comment]
Ok i you had free time then. Please one time try your repository on Codeanywhere.com 

It's free. 
I was trying on codeanywhere.com

**Comment by asapach** [comment]
I'm pretty sure that they are blocking bittorrent traffic, because it's against their [terms of service](https://codeanywhere.com/tos).
And Heroku simply terminates the app once they detect bittorrent.
If you want to host it do it yourself.

**Comment by nk932714** [comment]
Ok thanks a lot. Also thanks for your quick response.
