### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Bones80** [asapach/peerflix-server#120]
Hi,
Why is peerflix so slow getting torrents,is there something I could do to get better speeds any special configurations I might not have set up?

thanks

**Comment by asapach** [comment]
You can try opening port `6881` in your firewall and setting up port forwarding for tcp/udp bittorrent. When you have external connections enabled, it should be much faster.

**Comment by Bones80** [comment]
I believe this worked thanks!  Just got one more question does this work like a normal torrent program will I receive copyright notices?

**Comment by asapach** [comment]
Sure. It's a bittorrent client, so all the restrictions apply.

**Comment by Bones80** [comment]
oh ok ic... so this is not like those cloud torrent sites?

**Comment by asapach** [comment]
Nope. You run it, you host it, you can move it to the cloud if you want to (e.g. using [Docker](https://github.com/asapach/peerflix-server/blob/master/Docker.md)). But in the end you are responsible of how you use it.
"Those cloud torrent sites" work in a similar fashion, except they do it for you.

**Comment by Bones80** [comment]
Sorry again but was just wondering if you happen to know how to setup those cloud torrent sites,I know that Herokuapp site doesn't work anymore but they're are similar sites like codeanywhere.com or openshift.com would be a big help if not it's ok.   :)

**Comment by asapach** [comment]
Nope, sorry.
