### ISSUE TITLE
getting error while deploy on openshift

### ISSUE THREAD

**Issue by nk932714** [asapach/peerflix-server#121]
Can you add description about how to deploy this repo on Openshift
when i am trying to deploy i am getting this errror

----- logs-------

Cloning "https://github.com/asapach/peerflix-server.git" ... 	
Commit:	cfeb3363e770373bdd1890dea7ff10194e5e9100 (enabled node 8 in travis) 	
Author:	Aliaksei Sapach <aliaksei.dreamsonic@gmail.com> 	
Date:	Sun Aug 27 14:23:12 2017 +0300 
Pulling image "registry.access.redhat.com/rhscl/nodejs-4-rhel7@sha256:38e9ba4a2d9905d727601b3c364cdd7985688db2c3d6c4f6b447c7c4854acec1" ... 
---> Installing application source ...
 ---> Building your Node application from source 
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead 
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead 
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated 
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue 
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree. 
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree. 
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
 npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130 npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.6.2","npm":"2.15.1"}) 
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.6.2","npm":"2.15.1"}) npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.6.2","npm":"2.15.1"}) npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.6.2","npm":"2.15.1"}) npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.6.2","npm":"2.15.1"}) npm WARN optional dep failed, continuing fsevents@1.1.2  > phantomjs@1.9.20 install /opt/app-root/src/node_modules/karma-phantomjs-launcher/node_modules/phantomjs > node install.js  PhantomJS not found on PATH Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2 Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2 Receiving...

**Comment by asapach** [comment]
I don't see any errors, just the usual warnings. Haven't tried OpenShift, but might give it a go eventually.

**Comment by nk932714** [comment]
*while using npm start* i get the following error



> peerflix-server@0.2.0 start /home/app
--
  | > node ./server/bin.js
  |  
  | Listening on http://localhost:9000
  | /home/app/server/store.js:85
  | throw err;
  | ^
  |  
  | Error: EACCES: permission denied, mkdir '/.config'
  | at Error (native)
  |  
  | npm ERR! Linux 3.10.0-693.1.1.el7.x86_64
  | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
  | npm ERR! node v6.11.2
  | npm ERR! npm  v3.10.10
  | npm ERR! code ELIFECYCLE
  | npm ERR! peerflix-server@0.2.0 start: `node ./server/bin.js`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the peerflix-server@0.2.0 start script 'node ./server/bin.js'.
  | npm ERR! Make sure you have the latest version of node.js and npm installed.
  | npm ERR! If you do, this is most likely a problem with the peerflix-server package,
  | npm ERR! not with npm itself.
  | npm ERR! Tell the author that this fails on your system:
  | npm ERR!     node ./server/bin.js
  | npm ERR! You can get information on how to open an issue for this project with:
  | npm ERR!     npm bugs peerflix-server
  | npm ERR! Or if that isn't available, you can get their info via:
  | npm ERR!     npm owner ls peerflix-server
  | npm ERR! There is likely additional logging output above.
  | npm ERR! Linux 3.10.0-693.1.1.el7.x86_64
  | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
  | npm ERR! node v6.11.2
  | npm ERR! npm  v3.10.10
  | npm ERR! path npm-debug.log.2125781061
  | npm ERR! code EACCES
  | npm ERR! errno -13
  | npm ERR! syscall open
  |  
  | npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2125781061'
  | npm ERR!     at Error (native)
  | npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.2125781061'
  | npm ERR!     at Error (native)
  | npm ERR!   errno: -13,
  | npm ERR!   code: 'EACCES',
  | npm ERR!   syscall: 'open',
  | npm ERR!   path: 'npm-debug.log.2125781061' }
  | npm ERR!
  | npm ERR! Please try running this command again as root/Administrator.
  |  
  | npm ERR! Please include the following file with any support request:
  | npm ERR!     /home/app/npm-debug.log

**Comment by asapach** [comment]
Strange. It looks like they don't allow creating files in the home folder. We could ignore that error and carry on, but then again - what else don't they allow? I'll need to check it out.

**Comment by asapach** [comment]
I've spent a coupe of hours trying to figure out what's going on in the OpenShift console and my best guess is:
* When trying to set it up as a Node.js app, it just hangs on `npm install` because it seems to be running inside a resource-constrained 512MB container and just times out.
* When trying to run it as a Docker image it seems to have some weird permission issues, where it can neither run as `root`, nor as a custom user. They seem to have some rather specific requirements they expect from Docker images and I wasn't able to figure out the right combination.

I'd suggest going with their [starer kit](https://github.com/openshift/nodejs-ex) and just adding `peerflix-server` as a local npm dependency and just running it as `npm run peerflix-server`.

**Comment by nk932714** [comment]
ok thanks i will try with their starer kit @asapach
