### ISSUE TITLE
Running Multiple instances of peerflix-server

### ISSUE THREAD

**Issue by pavs** [asapach/peerflix-server#127]
I want to run multiple instances of peerflix-server with it's own config file (ie, peerflix-server -config2.json)
More specifically in regards to storing downloaded torrents location.

Is it possible?

**Comment by asapach** [comment]
I think you can run multiple instances if you specify a different `HOME` env for each one:
```bash
HOME=/tmp/1 peerflix-server
HOME=/tmp/2 peerflix-server
```
And something similar using `USERPROFILE` env on Windows.

**Comment by zQueal** [comment]
I've also confirmed this working with multiple unix users. Peerflix-server searches `~/.config/peerflix-server` for the configuration files. So a new user is able to spawn its own instance by specifying a new port;

    user1@host ~ # PORT=9000 peerflix-server &
    user1@host ~ # su user2
    user2@host ~ # PORT=9001 peerflix-server &
