### ISSUE TITLE
herokuapp

### ISSUE THREAD

**Issue by badboy95** [asapach/peerflix-server#129]
hello sir,
how can i use peerflix server on herokuapp i have seen many made peerflix server apps on herokuapp plz respond

**Comment by asapach** [comment]
You can try an older release: https://github.com/asapach/peerflix-server/tree/v0.1.2 - it has the "Deploy to Heroku" button.

**Comment by HimanshuChandolaa** [comment]
sir i am unable to deploy app in heroku...... problem with old version too.......  sir please tell how to deploy new version to heroku ? in older version i am getting build errorswhile deploying
