### ISSUE TITLE
Use official node image in dockerfile

### ISSUE THREAD

**Issue by sgsunder** [asapach/peerflix-server#133]
Is there any reason why you're not using Docker's official node image in your dockerfile? i.e replacing `FROM mhart/alpine-node:6` with `FROM node:6-alpine`.

The dockerfile builds and runs just as well with the change and I would assume that the official image is more secure.

**Comment by sgsunder** [comment]
Also, you can use `apk --no-cache add` instead of `apk update && apk add ... && rm -fr /var/cache/apk`. See this [blog post](http://blog.zot24.com/tips-tricks-with-alpine-docker/)

**Comment by asapach** [comment]
A PR is welcome.
