### ISSUE TITLE
Need help for create.

### ISSUE THREAD

**Issue by ghost** [asapach/peerflix-server#135]
I am not a professional devolover.I need help how to create a  simple torrent leeching site with peerflix-server.

"Please give me a instructions.

**Comment by asapach** [comment]
It's not really meant to be a public-facing web server: there's no security or flood protection. And it's not designed for leeching - the main goal is streaming/downloading torrents on demand. I wouldn't recommend it.

**Comment by iamfaiazahmed** [comment]
I want to make web like-
http://fanstechgh.herokuapp.com/#/

When I create to deploy in heroku.it shows build ecrror or somethings.but how the above website still running.

Please this request to you?Don't make disappoint?

**Comment by asapach** [comment]
See #98, #109, #128, #129, #132, etc.
Unfortunately Heroku no longer allows p2p apps. (However it looks like they didn't bother to remove the old ones.)
