### ISSUE TITLE
Start peerflix-server with linux

### ISSUE THREAD

**Issue by leo9595** [asapach/peerflix-server#144]
Is there a way to start peerflix-server next to linux? I tried via the line creating a file in the /etc/init.d/ folder but it did not work.
Can someone help me please?

**Comment by asapach** [comment]
You mean something like [this](https://github.com/asapach/peerflix-server/issues/10#issuecomment-61409423)?

**Comment by leo9595** [comment]
I tried, but I did not succeed.

**Comment by leo9595** [comment]
@asapach I made a small script that can be useful for this function with the `pgrep` command.

Works with cron.

Attention: The script can be useful if you use server only for **peerflix-server**. Because it checks to see if `node.js` is running. If you have other processes with `node.js` can of the problem. But who wants to improve the script, feel free.

Let's put in the folder "/root":
nano checar-peerflix

Paste the code:
I made a small script that can be useful for this function with the `pgrep `command.

Works with cron.

Attention: The script can be useful if you use server only for **peerflix-server**. Because it checks to see if node.js is running. If you have other processes with `node.js` can of the problem. But who wants to improve the script, feel free.

Let's put in the folder "/root":

`nano checar-peerflix`

Paste the code:

```
#!/bin/bash
#Scritp criado por: LPServidor
#Website: https://central.lpservidor.org

#--------------------------------------------------------#

#Verificar se o peerflix-server está rodando com o node.js

processo=$(pgrep "node")

if pgrep "node" > /dev/null
then
        echo "O peerflix-server está sendo executado com node neste momento."
        echo "Número do processo: $processo"
else
        echo "O peerflix-server não  está sendo executado. Tentandc ligar...\n"
        /usr/bin/peerflix-server
fi
```
save and put in cron to run every 1 minute, use the command `crontab -e`:

`* * * * * sh /root/checar-peerflix`

Save again.

Done!

The script will check every 1 minute whether the `node.js` is running or not. If you will not try to connect **peerflix-serve**r.

Sorry for my English, because I did a free translation on google translator, because I speak Brazilian Portuguese.

**Comment by leo9595** [comment]
@asapach I made a small script that can be useful for this function with the `pgrep` command.

Remember that the script is dependent on `cron`.

Attention: The script can be useful if you use server only for **peerflix-server**. Because it checks to see if `node.js` is running. If you have other processes with `node.js` can of the problem. But who wants to improve the script, feel free.

Let's put in the folder "/root":
`nano checar-peerflix`

Paste the code:

```
#!/bin/bash
#Scritp criado por: LPServidor
#Website: https://central.lpservidor.org

#--------------------------------------------------------#

#Verificar se o peerflix-server está rodando com o node.js

processo=$(pgrep "node")

if pgrep "node" > /dev/null
then
        echo "O node.js está sendo executado neste momento. Bem provalvel que o peerflix-server esteja funcionando!"
        echo "Número do processo: $processo"
else
        echo "Não foi detectado processo com o node.js, contudo o peerflix-server não está sendo executado. Tentando ligar...\n"
        /usr/bin/peerflix-server
fi
```
save and put in cron to run every 1 minute, use the command `crontab -e`:

`* * * * * sh /root/checar-peerflix`

Save again.

Done!

The script will check every 1 minute whether the `node.js` is running or not. If you will not try to connect **peerflix-server**.

Sorry for my English, because I did a free translation on google translator, because I speak Brazilian Portuguese.
