### ISSUE TITLE
Fix some files after download not opening

### ISSUE THREAD

**Issue by dachinat** [asapach/peerflix-server#148]
I have downloaded two files, zip and rar.

When I was downloading zip file, I clicked on filename to initiate a download, a file was downloaded to my drive and that zip would not open. When download on web-page completed, I re-downloaded file to my drive and then it opened.

Case with rar is different, it never opened, even after file was downloaded to server.

```
checksum error
Unexpected end of archive
Total errors: 2
```

However, when I checked if file itself was ok with some other torrent client it worked normally.

I'd like to somehow get this fixed if possible. I'll try look into the source, but I'd like know if you have encountered such behavior and do you have any plans or ideas about fixing this?

Thanks.

**Comment by asapach** [comment]
In order to fix it I need to reproduce it.

**Comment by dachinat** [comment]
Well, I'll reopen an issue if I'll have foundations for its reproduction. Thanks.
