### ISSUE TITLE
Problem with stream audio, using the mkv formats

### ISSUE THREAD

**Issue by MindOnFire93** [asapach/peerflix-server#155]
Hello, i have the problem with stream audio, using the mkv formats, stream work only using Chrome Browser, and in anyway the audio is disabled, for codec problem, how  i can solve that, and what web player for stream i need to use, i try to search and solve this, some and some days, but really i can't.. Thanks in advance, Mind

**Comment by asapach** [comment]
MKV is not really supported in any browsers natively. Chrome might try to treat it as WebM, but it still has only a limited set of supported codecs.
I recommend using an external player like VLC.

**Comment by MindOnFire93** [comment]
Thank you so much. Using the cloud player and stream as he source, i play mkv files with audio, for that i ask, in anyway i can not use that player, but that is possible..

**Comment by MindOnFire93** [comment]
Another one quwstio, i really don't know how to use ?remux, what node js need to be installed, for that, i god a nonb reply page, if i use ?remux at end of the file link. Thank you in advance. Mind

**Comment by asapach** [comment]
It was an experiment I tried -- see #19. I haven't used it in a while myself and not really sure if it still works.

**Comment by MindOnFire93** [comment]
Thanks, i try but i got no reply from the server, using WEBM.

**Comment by asapach** [comment]
Then I'm afraid it's broken.
