### ISSUE TITLE
Stream to an ip with port

### ISSUE THREAD

**Issue by dalton5** [asapach/peerflix-server#156]
Hi,

Such as peerflix is it possible to have a defined ip and port to stream to instead of having one adress like:

Current:
http://localhost:9000/torrents/5097c680f4f429ff795c9eec4ea8b30456211618/files/aaa.mp4

Wanted: 192.168.0.2:8000 for example

Thanks,

**Comment by asapach** [comment]
It's listening on all available interfaces, so any IP should work.
And you can configure the port using `PORT` [environment variable](https://github.com/asapach/peerflix-server#configuration).
