### ISSUE TITLE
Where is the config file

### ISSUE THREAD

**Issue by dalton5** [asapach/peerflix-server#158]
Hi

I am on windows and I try to find the config json file.

Nothing is in: C:\Users\user\AppData\Roaming\npm\node_modules\peerflix-server\server

Where is it please?

Thanks,

**Comment by asapach** [comment]
As [mentioned in README](https://github.com/asapach/peerflix-server#configuration) the file doesn't exist by default, so you need to create it yourself as `~/.config/peerflix-server/config.json`.
`~` means your HOME directory, so `C:\Users\user\.config\peerflix-server\config.json`
