### ISSUE TITLE
torrent-stream - vulnerability

### ISSUE THREAD

**Issue by megadrazz** [asapach/peerflix-server#166]
npm install --save torrent-stream
npm WARN magnetman@1.0.0 No repository field.

+ torrent-stream@1.1.0
added 76 packages from 37 contributors and audited 998 packages in 3.114s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Denial of Service

  Package         ws

  Patched in      >= 1.1.5 <2.0.0 || >=3.3.1

  Dependency of   torrent-stream

  Path            torrent-stream > torrent-discovery > bittorrent-tracker >
                  simple-websocket > ws

  More info       https://nodesecurity.io/advisories/550

found 1 high severity vulnerability in 998 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by asapach** [comment]
There is already an issue in torrent-stream: mafintosh/torrent-stream#191

**Comment by megadrazz** [comment]
ainda continua

npm install ws --save
npm WARN magnetman@1.0.0 No repository field.

+ ws@6.1.4
updated 1 package and audited 1000 packages in 4.087s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
