### ISSUE TITLE
Automatically resuming torrent

### ISSUE THREAD

**Issue by sagar17997** [asapach/peerflix-server#177]
Whenever I open the command of peerflix-server, it automatically resumes previous torrent file which then hangs the server and I'm not able to remove that file. Please help me to reset my peerflix server to initial point.

**Comment by asapach** [comment]
You can either remove `~/.config/peerflix-server/torrents.json` file to reset the state, or add the following option to `~/.config/peerflix-server/config.json` to disable resumption:
```json
{
  "verify": false
}
```

**Comment by sagar17997** [comment]
Sir how to do that using command prompt, can you please tell me the step? or is there any other way of doing that

**Comment by sagar17997** [comment]
Thank You so much for your help
