### ISSUE TITLE
upload functionality does not work

### ISSUE THREAD

**Issue by eugene55** [asapach/peerflix-server#180]
In log you can spot 500 status:
POST /upload 500 
Status message is: file is missing
With that, you can notice your torrent file with name like 4ZmsjwYfXUxKVJ718nv4Hey2.torrent that appeared in /tmp

node --version is v14.4.0

**Comment by asapach** [comment]
It looks like it's related to this issue: https://github.com/expressjs/connect-multiparty/issues/29

**Comment by asapach** [comment]
Should be fixed now.
