### ISSUE TITLE
previous state not found error in while launching peerflix-sever

### ISSUE THREAD

**Issue by akgithub89** [asapach/peerflix-server#190]
C:\Windows\System32>peerflix-server
Listening on http://localhost:9000
previous state not found

C:\Windows\System32>node -v
v10.9.0
C:\Windows\System32>npm -v
6.2.0

Tried with node 15.x also. Didnot work.

**Comment by asapach** [comment]
The message simply means that you're launching the server for the first time, so it doesn't have any previous state to load from.
