### ISSUE TITLE
No Web UI only REST api?

### ISSUE THREAD

**Issue by glblduh** [asapach/peerflix-server#191]
Is there a way to disable the web ui and only have the REST api running?

**Comment by asapach** [comment]
Your best option probably would be to create a fork and remove these lines: https://github.com/asapach/peerflix-server/blob/master/server/bin.js#L12-L14
If you think this would be useful as a CLI option, you could create a PR.

**Comment by glblduh** [comment]
Thanks, I'll try it tomorrow.

**Comment by glblduh** [comment]
Update it works, but I edited the files rather than making a fork.
