### ISSUE TITLE
:9000 port does not working...

### ISSUE THREAD

**Issue by nanedi** [asapach/peerflix-server#194]
:9000 port does not working...

**Comment by asapach** [comment]
any details?

**Comment by asapach** [comment]
I've tried vultr as well and got it working. You need to either disable the firewall or open the ports:
![image](https://user-images.githubusercontent.com/1755336/117541586-3d110d80-b01d-11eb-9c33-098e5590e546.png)
Debian also has its own firewall, so you can either disable or reconfigure it:
```sh
sudo ufw disable
```

**Comment by nanedi** [comment]
Thanks.
