### ISSUE TITLE
How to deploy it on IBM Cloud?

### ISSUE THREAD

**Issue by pipidaxian** [asapach/peerflix-server#200]
Hello! I have a problem. I pushed the repo to my IBM Cloud Foundry (CF), in the CLI Shell it seemed ok (as below), but the website just returned blank page. What can I do to correct my site? My website is [https://pipixia.eu-gb.cf.appdomain.cloud/](url)

The CLI Shell stated:

Staging app and tracing logs...
   Downloading go_buildpack...
   Downloading python_buildpack...
   Downloading swift_buildpack-deprecated...
   Downloading r_buildpack...
   Downloading liberty-for-java_v3_60-20210730-0620...
   Downloaded python_buildpack
   Downloaded liberty-for-java_v3_60-20210730-0620
   Downloading xpages_buildpack...
   Downloading xpages_buildpack_v1_2_1-20160913-103...
   Downloaded go_buildpack
   Downloading staticfile_buildpack...
   Downloaded r_buildpack
   Downloading java_buildpack...
   Downloaded swift_buildpack-deprecated
   Downloading ruby_buildpack...
   Downloaded xpages_buildpack_v1_2_1-20160913-103
   Downloading php_buildpack...
   Downloaded xpages_buildpack
   Downloading binary_buildpack...
   Downloaded staticfile_buildpack
   Downloading nginx_buildpack...
   Downloaded java_buildpack
   Downloading nodejs_buildpack...
   Downloaded ruby_buildpack
   Downloading liberty-for-java...
   Downloaded php_buildpack
   Downloading dotnet_core_buildpack...
   Downloaded binary_buildpack
   Downloading sdk-for-nodejs-deprecated...
   Downloaded nginx_buildpack
   Downloading sdk-for-nodejs_v4_6-20210305-2036-deprecated...
   Downloaded nodejs_buildpack
   Downloading sdk-for-nodejs_v4_5-20201130-1530-deprecated...
   Downloaded liberty-for-java
   Downloading liberty-for-java_v3_59-20210701-1053...
   Downloaded sdk-for-nodejs-deprecated
   Downloading sdk-for-nodejs...
   Downloaded dotnet_core_buildpack
   Downloaded sdk-for-nodejs_v4_6-20210305-2036-deprecated
   Downloaded sdk-for-nodejs_v4_5-20201130-1530-deprecated
   Downloaded liberty-for-java_v3_59-20210701-1053
   Downloaded sdk-for-nodejs
   Cell 114168e8-f230-42b2-9fd8-109c2822c2da creating container for instance 15dc91b2-c166-4d06-8429-bfe45d4facd6
   Cell 114168e8-f230-42b2-9fd8-109c2822c2da successfully created container for instance 15dc91b2-c166-4d06-8429-bfe45d4facd6
   Downloading build artifacts cache...
   Downloading app package...
   Downloaded app package (410.2K)
   Downloaded build artifacts cache (45.6M)
   -----> Nodejs Buildpack version 1.7.57
          **WARNING** buildpack version changed from 1.7.48 to 1.7.57
   -----> Installing binaries
          engines.node (package.json): >=6
          engines.npm (package.json): unspecified (use default)
          **WARNING** Dangerous semver range (>) in engines.node. See: http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
   -----> Installing node 16.5.0
          Download [https://buildpacks.cloudfoundry.org/dependencies/node/node_16.5.0_linux_x64_cflinuxfs3_4801df19.tgz]
          Using default npm version: 7.19.1
   -----> Installing yarn 1.22.10
          Copy [/tmp/cache/final/dependencies/12a37598b7228940e2461866d4a9e47d1c396fe04bd207f9b647ca793ad79aa8/yarn_1.22.10_linux_noarch_any-stack_0057c1c9.tgz]
          Installed yarn 1.22.10
   -----> Creating runtime environment
          PRO TIP: It is recommended to vendor the application's Node.js dependencies
          Visit http://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring
          NODE_ENV=production
          NODE_HOME=/tmp/contents405934697/deps/0/node
          NODE_MODULES_CACHE=true
          NODE_VERBOSE=false
          NPM_CONFIG_LOGLEVEL=error
          NPM_CONFIG_PRODUCTION=true
   -----> Building dependencies
          Installing node modules (package.json + package-lock.json)
   added 309 packages, and audited 310 packages in 26s
   6 packages are looking for funding
     run `npm fund` for details
   3 vulnerabilities (1 low, 2 high)
   To address all issues, run:
     npm audit fix
   Run `npm audit` for details.
   npm notice 
   npm notice New minor version of npm available! 7.19.1 -> 7.21.1
   npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.21.1>
   npm notice Run `npm install -g npm@7.21.1` to update!
   npm notice 
          **WARNING** Unmet dependencies don't fail npm install but may cause runtime issues
          See: https://github.com/npm/npm/issues/7494
          Contrast Security no credentials found. Will not write environment files.
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading droplet...
   Uploading build artifacts cache...
   Uploaded build artifacts cache (63.1M)
   Uploaded droplet (38.9M)
   Uploading complete
   Cell 114168e8-f230-42b2-9fd8-109c2822c2da stopping instance 15dc91b2-c166-4d06-8429-bfe45d4facd6
   Cell 114168e8-f230-42b2-9fd8-109c2822c2da destroying container for instance 15dc91b2-c166-4d06-8429-bfe45d4facd6
   Cell 114168e8-f230-42b2-9fd8-109c2822c2da successfully destroyed container for instance 15dc91b2-c166-4d06-8429-bfe45d4facd6

Waiting for app to start...

name:              XXX
requested state:   started
routes:            XXX
last uploaded:     Tue 31 Aug 13:19:03 UTC 2021
stack:             cflinuxfs3
buildpacks:        nodejs

type:            web
instances:       1/1
memory usage:    256M
start command:   npm start
     state     since                  cpu    memory          disk           details
#0   running   2021-08-31T13:19:18Z   0.3%   55.6M of 256M   176.1M of 1G

**Comment by asapach** [comment]
It's hard to say what's wrong with it. If the app starts correctly you should see this message: https://github.com/asapach/peerflix-server/blob/afe84359e7e06ce36999737b494e2a8192cf0c66/server/bin.js#L27
I don't see it in the log, but I also don't see any errors, so I'm not sure what's happening.
