### ISSUE TITLE
Can't start peerflix-server

### ISSUE THREAD

**Issue by keroum** [asapach/peerflix-server#25]
Hello When I type peerflix-server i get this, knowing that It's been working fine , It's running Ubuntu 14.04

root@ns310445:~#  peerflix-server
   info  - socket.io started
undefined:0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/peerflix-server/server/store.js:101:29
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)

**Comment by asapach** [comment]
Try deleting your `~/.config/peerflix-server/torrents.json` file. It looks like it might be corrupted.

**Comment by keroum** [comment]
Thank you! You're a life saver

**Comment by asapach** [comment]
np :blush:
