### ISSUE TITLE
How to start/stop torrents from REST api?

### ISSUE THREAD

**Issue by iShift** [asapach/peerflix-server#28]
From web ui i can start/stop torrent, how can i do this fro api?

**Comment by asapach** [comment]
Currently you can only do it using websocket api (undocumented). Any suggestions how you would expect to see it in the rest api?

**Comment by iShift** [comment]
GET /torrents/{infoHash}/action 
where action is (stop, pause,start)

**Comment by brunocascio** [comment]
I think is better `POST` instead of `GET`, because you don't get nothing from server else you'll send stop/pause/play method.

**Comment by asapach** [comment]
@brunocascio, I agree

**Comment by asapach** [comment]
fixed by #30
