### ISSUE TITLE
Specified physical interface

### ISSUE THREAD

**Issue by iShift** [asapach/peerflix-server#29]
How can i start peerflix server only on one physical interface?

**Comment by asapach** [comment]
See mafintosh/torrent-stream#108

**Comment by iShift** [comment]
> hmm, maybe add new option to peerflix - network interface?

**Comment by asapach** [comment]
And what will this option do exactly? Until torrent-stream supports multiple interfaces there's nothing to be done in peerflix-server.

**Comment by iShift** [comment]
Bind only to one interface, not to all
