### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by milankragujevic** [asapach/peerflix-server#32]
Is it planned to add some kind of authentication, so that if I use this as a seedbox or for my project (https://github.com/milankragujevic/WebMovBucket) I can have control over who's using it?

**Comment by asapach** [comment]
As mentioned in #18, I consider auth out of scope of this project. *Today* you can implement your own by placing a reverse proxy server in front of peerflix-server, e.g. nginx.

*In the future* I'm playing with the idea of creating an infrastructure that would allow developers to create plugins (both on the front-end and the back-end). If you have some suggestions or ideas how this should be implemented, I would appreciate for some feedback.

**Comment by milankragujevic** [comment]
Thank you for your response. I will update my fork with a simple HTTP auth interface that can be configured from a config file, and uses a default password of admin/admin if password is not set up.
