### ISSUE TITLE
Install it in another drve

### ISSUE THREAD

**Issue by ArdiArtani** [asapach/peerflix-server#37]
how to install it in my F drive??

I did in cmd first
1. F:
2. created a folder peerflix, in cmd entered cd peerflix
3. npm install  -g peerflix-server
4. peerflix

and the temp folder to bo in F drive where the downloaded movies store

**Comment by asapach** [comment]
What you really want is to override the default configuration: create a new file `C:\Users\<user>\.config\peerflix-server\config.json` and paste this:

```json
{
  "tmp": "f:/<your-folder>"
}
```

**Comment by ArdiArtani** [comment]
it worked :)

one more question i want the peerflix-server folder to be too on F drive the one that is installed in C:\Users\<user>\AppData\Roaming\npm\node_modules

how can i do that ??

**Comment by asapach** [comment]
When you run `npm -g i`, it will install with the rest of the global npm modules.
If you run `npm i` without `-g`, it will install into the current folder, but it will no longer be in the `PATH`, so you'll have to call it by full path, or by running `npm start` when you `cd` inside `node_modules`.

**Comment by ArdiArtani** [comment]
thank you :)
