### ISSUE TITLE
Upload torrent not working

### ISSUE THREAD

**Issue by mistertest** [asapach/peerflix-server#38]
Hello, great app but upload not work on local or true server.
Need help for this .

thx.

**Comment by AMerkuri** [comment]
You mean "browse to upload" doesn't work as in http://i.imgur.com/nwXdoT3.png ?
It works perfectly fine for me, try other browser.

**Comment by mistertest** [comment]
Hello, Yes the drag and drop work well, but on my android tv box , it's not possible for use with tablet browsers. So i must have use the basic upload but it'not workk. The browse file with file explorer work but not the upload function. I must have to create a upload.php or something like that with dat of my server ??

**Comment by asapach** [comment]
OK, what browser are you on and what file are you trying to upload?

**Comment by mistertest** [comment]
Ok thx, firefox on pc and firefox version tablet same things with google.

**Comment by mistertest** [comment]
And Aspach, i whant to upload .torrent from my download folder.

**Comment by mistertest** [comment]
For the moment I can do without it because I have integrated my favorites trackers and I use the copy and paste links and magnets torrents

**Comment by mistertest** [comment]
Great great Ap asapach ! very good work.

**Comment by mistertest** [comment]
And i use peerflix server on a vps ubuntu and on localhost in my computer on ubuntu 14.04 to.And i have same problems. Have you code it on linux ?

**Comment by mistertest** [comment]
I know that with my changes for using copy and paste . Browse a file is no longer so important , but I would still like it to work .

**Comment by mistertest** [comment]
Excuse guys my frenchglish

**Comment by asapach** [comment]
> Have you code it on linux ? 

Yes, I run it both on linux and windows and it works fine for me.

Do you see any messages in the console that look like errors?

Can you send the link to the torrent file you're trying to upload?

**Comment by mistertest** [comment]
Ok it's the same with any torrent not with one a particular. For the console i put it later and you will see anytime you want, it's not urgent and i don't want to give your  time.

**Comment by mistertest** [comment]
It works very well. Maybe you could add the functions " select all " and " simply remove all " and " all pause " of i can do it myself, thx.

**Comment by asapach** [comment]
>It works very well. Maybe you could add the functions " select all " and " simply remove all " and " all pause " of i can do it myself, thx.

OK, please create another issue for this.

**Comment by asapach** [comment]
See #40

**Comment by mistertest** [comment]
Hello file upload is working well now in my new web hosting certainly a problem from node js installation. Thx
