### ISSUE TITLE
which part of the code do i use if i need to stream torrent to a video element in html using peerflix ?

### ISSUE THREAD

**Issue by saru95** [asapach/peerflix-server#47]

**Comment by mikael-came** [comment]
Hi,
I think you can call the api  URL : /torrents/"+HASH+"/files/"+FILENAME

**Comment by asapach** [comment]
Files have the `link` property which you can use: https://github.com/asapach/peerflix-server/blob/master/server/index.js#L42

**Comment by saru95** [comment]
Thanks !
