### ISSUE TITLE
Upload seems to end when download is complete

### ISSUE THREAD

**Issue by GautierThiriez** [asapach/peerflix-server#57]
Hi, 
Upload seems to end when downloading the files is over. 
It's a bug or a features ? It's should be a option !
It will be better for p2p community... 
Thanks!

**Comment by asapach** [comment]
It depends on the torrent. If there are many seeders, once you've downloaded the files, there are few leechers to share it with. If on the other hand there are few seeders, you will become one and will continue to seed.
It also depends on your network: for example if you have port forwarding enabled on port 6881 you will get more peers.

**Comment by GautierThiriez** [comment]
Thanks for your answer.
It's just seems to upload a lot during download and stop when download was complete but must fate !
