### ISSUE TITLE
html5 seeking video control with ffmpeg=remux url parameter issue

### ISSUE THREAD

**Issue by shokohsc** [asapach/peerflix-server#59]
Hello, i can't seem to go forward/backward on the video when i use ?ffmpeg=remux
No logs shows any error but it just doesn't work, tis ok when watching a mp4 file though without the ffmpeg=remux url parameter.

**Comment by asapach** [comment]
Unfortunately seeking won't work for transcoded streams as explained [here](https://github.com/asapach/peerflix-server/issues/20#issuecomment-82252626).

**Comment by shokohsc** [comment]
Oh ok, thanks, i now know what transcoding is.
