### ISSUE TITLE
How hidden the files are not videos with somes js ?

### ISSUE THREAD

**Issue by mistertest** [asapach/peerflix-server#60]
Hello the team, happy good year and thank you for your great tool.
How hide the files  that  are not videos with somes  Javascript or jquery functions ? Or there is a definite class like {torrent:file video } something like that ?

thank you.

**Comment by asapach** [comment]
Your best bet would probably be go through each file in a torrent and filter it by extension. For example go through the `torrents` array and then through `torrent.files` array and inspect the `file.name` property to see if it matches known video extensions, e.g. `.mp4`

**Comment by mistertest** [comment]
Hello yes this is the idea, but jquery function for the filter and add class is not working with this angular app. I don't know the programming with angular
I want integrate a audio player directly in the view i continue my researches
