### ISSUE TITLE
ffmpeg - how to install on  heroku

### ISSUE THREAD

**Issue by maciek9991** [asapach/peerflix-server#61]
Hello. I want use remux my torrent on heroku cloud. But I don't known how to do this :) Can anybody help me with this problem?

**Comment by debpalash** [comment]
go https://github.com/asapach/peerflix-server click on the deploy to heroku link. login to heroku and follow instructions. skype me id-polashdeb

**Comment by maciek9991** [comment]
Yeah, I know how to "deploy to Heroku" in one click. The problem is that when I want to use remux I get an "application error". I try install ffmpeg via Heroku CLI and change PATH but without any success.
