### ISSUE TITLE
How to change Peerflix storage ?

### ISSUE THREAD

**Issue by JYOUSSEF** [asapach/peerflix-server#64]
Hi @asapach  thank You for sharing this beautiful peerflix-server with us.
I just have a question about peerflix storage : is there any option to change storage from Server storage (HDD or RAM) to Client Storage (IndexedDB,....)
I want to store the readable stream chunks in client browser IndexeDB and then stream them to the browser.
Thank you in advance for any help you can provide !

**Comment by asapach** [comment]
There's a project called WebTorrent that tries to implement this: https://github.com/feross/webtorrent/issues/86
