### ISSUE TITLE
[question] file size control !

### ISSUE THREAD

**Issue by yas9999** [asapach/peerflix-server#66]
Hello,
there is any option to limit torrent size ?
example: if files are more than 10 GB it won't be downloaded or maybe pop an error message (file is large than 10 GB)

Best regards

**Comment by asapach** [comment]
Well, if you don't want to download it just uncheck the checkbox next to the file. I sometimes stream files that are several GB in size, so I don't really think this option should be on by default.

**Comment by yas9999** [comment]
yeah i know, but i will not only the one who will use peerflix in my server !
maybe 100 users or more that's why i'm asking about file size limit.

regards,

**Comment by asapach** [comment]
The problem is that it hasn't been designed with multi-user support in mind: there are no user sessions or quotas, etc.

**Comment by yas9999** [comment]
yes you have right ! as you know not all users are able to have a server or how to setup peerflix
that why i wanna make it for multi users ... maybe it will be possible but need more coding :+1: 

thank you so much @asapach
