### ISSUE TITLE
 I run 9000 port, and I just saw loge , the page didn't  show  anything. 

### ISSUE THREAD

**Issue by martin823823** [asapach/peerflix-server#68]

**Comment by martin823823** [comment]
GET /bower_components/bootstrap/dist/css/bootstrap.css 404 18ms
GET /bower_components/angular-route/angular-route.js 404 14ms
GET /bower_components/lodash/dist/lodash.compat.js 404 14ms
GET /bower_components/font-awesome/css/font-awesome.css 404 15ms
GET /bower_components/jquery/dist/jquery.js 404 14ms
GET /bower_components/angular/angular.js 404 14ms
GET /bower_components/angular-resource/angular-resource.js 404 8ms
GET /bower_components/angular-cookies/angular-cookies.js 404 9ms
GET /bower_components/angular-sanitize/angular-sanitize.js 404 7ms
GET /bower_components/bootstrap/dist/js/bootstrap.js 404 7ms
GET /bower_components/angular-socket-io/socket.js 404 8ms
GET /bower_components/ng-file-upload/angular-file-upload.js 404 7ms

**Comment by asapach** [comment]
Have you installed it from npm or are you running from source?

**Comment by martin823823** [comment]
I had installed it from npm. I also run from source. but the "main.html" did't show. 


macdeMacBook-Pro:server mac$ node bin.js
   info  - socket.io started
previous state not found
GET / 304 8ms
GET /bower_components/bootstrap/dist/css/bootstrap.css 404 6ms
GET /bower_components/jquery/dist/jquery.js 404 7ms
GET /bower_components/font-awesome/css/font-awesome.css 404 7ms
GET /styles/main.css 304 10ms
GET /bower_components/angular/angular.js 404 7ms
GET /bower_components/angular-resource/angular-resource.js 404 8ms
GET /bower_components/angular-cookies/angular-cookies.js 404 9ms
GET /bower_components/angular-sanitize/angular-sanitize.js 404 11ms
GET /bower_components/angular-route/angular-route.js 404 10ms
GET /bower_components/bootstrap/dist/js/bootstrap.js 404 10ms
GET /bower_components/lodash/dist/lodash.compat.js 404 2ms
GET /bower_components/angular-socket-io/socket.js 404 2ms
GET /bower_components/ng-file-upload/angular-file-upload.js 404 11ms
GET /scripts/controllers/main.js 304 11ms
GET /scripts/services/torrent-socket.js 304 11ms
GET /scripts/app.js 200 211ms - 604b

**Comment by asapach** [comment]
Read this first if you want to run it from source: https://github.com/asapach/peerflix-server/blob/master/Development.md

**Comment by martin823823** [comment]
thanks
