### ISSUE TITLE
Accessing Web UI on another device on WiFi network

### ISSUE THREAD

**Issue by harryludson** [asapach/peerflix-server#72]
localhost:9000 works on the same device but accessing it from another computer / tablet using local IP (such as 10.0.0.1) results in 'connection refused'. Is this something that I can change in peerflix-server or is it more to do with my computer's network setup? I'm running Windows 10 and trying to access from a Google Pixel C tablet. Thanks for all your hard work.

EDIT: Just got it working after directly running 'peerflix-server', I was trying to get it to work through forever as a daemon. Must be an issue with my forever config.

**Comment by asapach** [comment]
Just use http://10.0.0.1:9000/
