### ISSUE TITLE
progress bar , speed, traffic queue and peers still show up when download completed 

### ISSUE THREAD

**Issue by buziyborni** [asapach/peerflix-server#73]
As i said first i was testing the app but it
seem like after the download completed the progress bar , speed, traffic queue and peers 
still show up how to do i make it vanish after
download completed. I was trying to make it with css but it didn't work

**Comment by asapach** [comment]
It depends on your definition of "complete". Unfortunately the underlying library ([torrent-stream](/mafintosh/torrent-stream)) doesn't have an indication when all the files have been downloaded, so you can't tell if there's nothing selected (so the server is idle) or the torrent is 100% downloaded and it's seeding.
If "idle" is good enough for you can rely on the following classes:
* Each torrent has a `div.panel` container
* When a torrent is fetching metadata it has `panel-warning` class
* When it's "interested" and downloading something it has `panel-success` class

So what you can do is hide the progressbar (`div.progress`) and footer (`div.panel-footer`) for all cases except `panel-success`.

**Comment by buziyborni** [comment]
Thanks sir will try and give you feedback
