### ISSUE TITLE
i cannot install this correctly.

### ISSUE THREAD

**Issue by wjm2038** [asapach/peerflix-server#85]
npm http GET https://registry.npmjs.org/peerflix-server
npm http 304 https://registry.npmjs.org/peerflix-server
npm ERR! TypeError: Arguments to path.resolve must be strings
npm ERR!     at Object.win32.resolve (path.js:146:13)
npm ERR!     at Object.win32.relative (path.js:269:16)
npm ERR!     at installOne_ (C:\nodejs\node_modules\npm\lib\install.js:693:26)
npm ERR!     at installOne (C:\nodejs\node_modules\npm\lib\install.js:621:3)
npm ERR!     at C:\nodejs\node_modules\npm\lib\install.js:508:9
npm ERR!     at C:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:54:35
npm ERR!     at Array.forEach (native)
npm ERR!     at C:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:54:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (C:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:53:8)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "peerflix-server"
npm ERR! cwd C:\Users\wjm
npm ERR! node -v v0.12.9
npm ERR! npm -v 1.1.61
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\wjm\npm-debug.log
npm ERR! not ok code 0

**Comment by wjm2038** [comment]
that one was solved, but I got a new problem now.
c:\users\wjm\.node-gyp\0.10.25\deps\uv\include\uv-private/uv-win.h(32): fatal error C1083: Cannot open include file: 'w
insock2.h': No such file or directory [C:\Users\wjm\AppData\Roaming\npm\node_modules\peerflix-server\node_modules\socke
t.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
Project : warning PRJ0018: The following environment variables were not found: [C:\Users\wjm\AppData\Roaming\npm\node_m
odules\peerflix-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
c:\users\wjm\.node-gyp\0.10.25\deps\uv\include\uv-private/uv-win.h(32): fatal error C1083: Cannot open include file: 'w
insock2.h': No such file or directory [C:\Users\wjm\AppData\Roaming\npm\node_modules\peerflix-server\node_modules\socke
t.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
Project : warning PRJ0018: The following environment variables were not found: [C:\Users\wjm\AppData\Roaming\npm\node_m
odules\peerflix-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]

**Comment by asapach** [comment]
Try installing this first: https://github.com/felixrieseberg/windows-build-tools

**Comment by asapach** [comment]
Also node 0.x is dead; use version 4+.

**Comment by asapach** [comment]
Please try the latest version. Should be fixed now.
