### ISSUE TITLE
Add Ability to Upload Torrents Directly to Google Drive And One Drive : Add Backend Storage Support

### ISSUE THREAD

**Issue by bulltech** [asapach/peerflix-server#86]
Lets Take It To Next Level

**Comment by maxerbox** [comment]
https://sites.google.com/site/gdocs2direct/

**Comment by maxerbox** [comment]
Websites like that, can do the trick.

**Comment by bulltech** [comment]
i mean to add backend support

**Comment by AnasQiblawi** [comment]
some websites i used in an old Research i did that might be very useful for you 
--------------------------------------------------------------------------
Remote Upload 

go4up.com
http://urltocloud.nsspot.net/
https://thoaimedia.com/save/
http://ctrlq.org/save/
https://leech.thoaimedia.com/

http://www.autogeneratelink.com/
http://youtubemultidownloader.com/index.html
