### ISSUE TITLE
running on 80 port

### ISSUE THREAD

**Issue by salientroot** [asapach/peerflix-server#87]
Hi,

I am using the peerflix-server app now and it is working well.
But I want to run on 80 port.
Could do you explain about it?

Thanks,
Salient

**Comment by asapach** [comment]
You can set `PORT` environment variable like so (in bash):
```sh
PORT=80; peerflix-server
```

But then you'll need to run it under root or sudo (because ports under 1024 are restricted), and I would not recommend it, because it's a potential security vulnerability.

Instead I would recommend setting up a reverse proxy server like nginx or apache to proxy the traffic from peerflix-server.

**Comment by salientroot** [comment]
Thanks for your help, but I tried and it is not working yet.

**Comment by salientroot** [comment]
Hi asapach,

I can run the app with port 80 now.
And i want to run the app as grunt with persistence
could you help me about it?

Thanks,
Salient

**Comment by asapach** [comment]
What do you mean by running it as grunt? What kind of persistence do you have in mind?

**Comment by salientroot** [comment]
i think the app is running with grunt serve command to customize.
Otherwise it is running with peerflix-server. 
Now if i run the grunt serve and the command end, the app is not running.
Could i execute it continuously?

**Comment by asapach** [comment]
You should not be running it via grunt. This is only for development mode. You should install it globally: `npm install -g peerflix-server` and run it as a daemon: https://github.com/asapach/peerflix-server#daemon
To run it continuously use `forever`: https://github.com/foreverjs/forever

**Comment by salientroot** [comment]
yeah, but I changed some html and it didn't implement when i run the with peerflix-server.

**Comment by asapach** [comment]
OK, instead of running `grunt server` you should just be able to run `<path to peerflix-server>/server/bin.js`, and then you should be able to use it with `forever`

**Comment by salientroot** [comment]
could you teach me in more details?

**Comment by chopraaa** [comment]
Running it with with `forever` doesn't lead to anything unfortunately. Page doesn't load.

**Comment by asapach** [comment]
@chopraaa, works fine for me. Enable the logs and see if there are any errors: https://github.com/foreverjs/forever#command-line-usage (I'd rather create a separate issue if there are.)

Having said that, I still don't recommend running it on port 80 directly.
