### ISSUE TITLE
Fatal error: Invalid string length

### ISSUE THREAD

**Issue by SuperDisk** [asapach/peerflix-server#90]
I can run the program fine by installing via `npm` and running `peerflix-server`, but when I clone the git repository, run `npm install` and `bower install`, then try to stream a video file, the server console (`grunt serve`) waits for a little while before outputting `Fatal error: Invalid string length` and no other info... Not really sure what's going on. For what it's worth, if I start the stream in my browser with the `peerflix-server` started instance, close it and switch to the `grunt serve` version, I can skip around in the file correctly, implying it's streaming. It just can't get it started or something.

I'm using Windows 10 and Node 6, if it matters.

Edit: Non-video files can still be downloaded like normal (images, text files, etc)

**Comment by asapach** [comment]
Have you figured out what the issue was? Do you have any repro steps?
