### ISSUE TITLE
the cached torrent file get deleted

### ISSUE THREAD

**Issue by Faisals619** [asapach/peerflix-server#92]
i install it correctly with heroku and i use torrent link to cache but when i close my browser and open again, i can't find the cached link. why it doesn't stay forever? any solution please.

**Comment by asapach** [comment]
My guess is that heroku have just deleted all the temp data. It's not really designed for long-running processes, especially if you're using a free account.

**Comment by asapach** [comment]
Here's the [quote](https://www.heroku.com/pricing#dyno-comparison):
> Sleeps after 30 mins of inactivity, otherwise always on depending on your remaining monthly free dyno hours.

**Comment by Faisals619** [comment]
So what should i do? Should i buy premium heroku account or get any other cloud storage? I want my cached torrent links to stay always alive.

**Comment by Faisals619** [comment]
So what should i do? Should i buy premium heroku account or get any other cloud storage? I want my cached torrent links to stay always alive.

**Comment by Faisals619** [comment]
So what should i do? Should i buy premium heroku account or get any other cloud storage? I want my cached torrent links to stay always alive.

**Comment by asapach** [comment]
If you want it to stay up forever you will either have to spin up your own server, or pay somebody to host it for you. It doesn't matter which hosting provider you choose.

**Comment by WiZMalik420** [comment]
I want to host the app in other hosting provider.is any free hosts available??

**Comment by asapach** [comment]
Sorry, this is off-topic. I'm going to close this issue.
