### ISSUE TITLE
some torrents stuck at "fetching metadata"

### ISSUE THREAD

**Issue by torrent123qwe** [asapach/peerflix-server#97]
This torrent: http://rarbg.to/torrent/9nadgs3 

After I created my own cloud with your peerflix server I leeched Above torrent,
But stuck at "fetching metadata" for so many hours: http://i.imgur.com/CkBWEen.jpg

**Comment by asapach** [comment]
Yeah, the underlying libraries get stuck if the torrent is not very popular, i.e. if there's no tracker or very few peers, also sometimes it can take a while to traverse DHT. Not sure that this can be fixed.
