### ISSUE TITLE
Heroku Failure

### ISSUE THREAD

**Issue by smartkidag** [asapach/peerflix-server#98]
Heroku is deleting the app withing seconds of its creation. I tried it multiple times. Any reason? 
Thanks!

**Comment by asapach** [comment]
Yeah, I think it might violate their new terms of service. I've seen similar apps banned.

**Comment by asapach** [comment]
I've removed any mention of Heroku from the project.

**Comment by smartkidag** [comment]
Is there any alternative to heroku? Anything which works in similar way?

**Comment by asapach** [comment]
Any cloud/hosting provider will do as long as they support Node.js and/or Docker. Heroku simply had this one-click install which is their killer feature.

**Comment by asapach** [comment]
I would avoid any US-based companies though, since they fear DMCA as a plague and ban any torrent apps.

**Comment by smartkidag** [comment]
Can you suggest the best alternative? Thanks!

**Comment by asapach** [comment]
Host it yourself :)

**Comment by smartkidag** [comment]
I tried but I can't due to some reasons. That's the only problem. :(

**Comment by smartkidag** [comment]
The issue is not technical. I'm not so good at code. I just loved your peerflix idea. I used it to download. Thanks btw. :)

**Comment by AnasQiblawi** [comment]
how can i host your work on a normal hosting website such as comxa
